# Generated by Django 4.1.1 on 2022-09-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
